### ISSUE TITLE
`field-of-rationals.pluto` doesn't terminate

### ISSUE THREAD

**Issue by srid** [Plutonomicon/pluto#11]
This runs forever,

```
cabal run pluto -- run examples/field-of-rationals.pluto
```

**Comment by ursi** [comment]
This is because `fix`. Once you work around that, you run into #12

**Comment by srid** [comment]
It looks like this got fixed.

`field-of-rationals.pluto` evaluates to a lambda. I don't know whether it is correct, but it does terminate.
